Update Jenkinsfile

diff --git a/epc-frontend-main/Jenkinsfile b/epc-frontend-main/Jenkinsfile
--- a/epc-frontend-main/Jenkinsfile
+++ b/epc-frontend-main/Jenkinsfile
@@ -5,7 +5,7 @@ pipeline {
         AWS_REGION = "ap-south-1"
         ECR_REPO = "924263791418.dkr.ecr.ap-south-1.amazonaws.com/epc-frontend"
         IMAGE_TAG = "${BUILD_NUMBER}"
-        FRONTEND_SERVER = "13.207.57.145"
+        FRONTEND_SERVER = "65.1.85.177"
     }
 
     stages {
@@ -67,22 +67,22 @@ pipeline {
             }
         }
 
-        stage('Deploy to Frontend UAT') {
+        stage('Deploy to Frontend Production') {
             steps {
                 sshagent(credentials: ['frontend-key']) {
                     sh """
                     ssh -o StrictHostKeyChecking=no ubuntu@${FRONTEND_SERVER} '
-                    aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin 924263791418.dkr.ecr.ap-south-1.amazonaws.com
+                    aws ecr get-login-password --region ${AWS_REGION} | sudo docker login --username AWS --password-stdin 924263791418.dkr.ecr.ap-south-1.amazonaws.com
 
-                    docker pull ${ECR_REPO}:${IMAGE_TAG}
+                    sudo docker pull ${ECR_REPO}:${IMAGE_TAG}
 
-                    docker stop epc-frontend || true
-                    docker rm epc-frontend || true
+                    sudo docker stop epc-frontend || true
+                    sudo docker rm epc-frontend || true
 
-                    docker run -d \
+                    sudo docker run -d \
                       --name epc-frontend \
                       -p 80:80 \
-                      --restart unless-stopped \
+                      --restart always \
                       ${ECR_REPO}:${IMAGE_TAG}
                     '
                     """
@@ -93,11 +93,15 @@ pipeline {
 
     post {
         success {
-            echo 'Pipeline executed successfully.'
+            echo 'Production deployment completed successfully.'
         }
 
         failure {
-            echo 'Pipeline execution failed.'
+            echo 'Production deployment failed.'
+        }
+
+        always {
+            cleanWs()
         }
     }
 }
